### ISSUE TITLE
Basler camera support?

### ISSUE THREAD

**Issue by Antorithms** [JARVIS-MoCap/JARVIS-AcquisitionTool#5]
Hi,
Are you by any chance planning to implement support for Basler Ace2 cameras ? 
( https://www.baslerweb.com/en/products/cameras/area-scan-cameras/ace2/a2a1920-160umpro/ )
If so what would be the expected timeline?
Otherwise do you think it would be feasible and or very time-consuming ? 
Thanks a lot in advance!

**Comment by JARVIS-MoCap** [comment]
After looking into it some more we have decided to not implement support for any other camera manufacturer in the near future, due to the complexity of implementing this in the current AcquisitionTool architecture, so I'll close this issue for now.

That being said, after some initial testing [Aravis](https://github.com/AravisProject) looks incredibly promising. This would allow using any USB3/GigE camera that follows the GeniCam standrard (FLIR, Basler, Ximea, ImagingSource,...), so there is potential for a much more flexible rewrite of the AcquisitionTool in the future,
