### ISSUE TITLE
Error during cmake of Qt6

### ISSUE THREAD

**Issue by JonathanAMichaels** [JARVIS-MoCap/JARVIS-AcquisitionTool#7]
CMake Warning at /home/pruszynskilab/Desktop/JARVIS-AcquisitionTool/libs/Qt/build/qtbase/lib/cmake/Qt6/Qt6Config.cmake:213 (find_package):
  Found package configuration file:

    /home/pruszynskilab/Desktop/JARVIS-AcquisitionTool/libs/Qt/build/qtbase/lib/cmake/Qt6Core/Qt6CoreConfig.cmake

  but it set Qt6Core_FOUND to FALSE so package "Qt6Core" is considered to be
  NOT FOUND.
Call Stack (most recent call first):
  qtimageformats/CMakeLists.txt:13 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/pruszynskilab/Desktop/JARVIS-AcquisitionTool/libs/Qt/build/CMakeFiles/CMakeOutput.log".
See also "/home/pruszynskilab/Desktop/JARVIS-AcquisitionTool/libs/Qt/build/CMakeFiles/CMakeError.log".
CMake Error at /home/pruszynskilab/Desktop/JARVIS-AcquisitionTool/libs/Qt/qt/qtbase/cmake/QtProcessConfigureArgs.cmake:963 (message):
  CMake exited with code 1.

make: Makefile: No such file or directory
make: *** No rule to make target 'Makefile'.  Stop.
CMake Error: Error processing file: /home/pruszynskilab/Desktop/JARVIS-AcquisitionTool/libs/Qt/build/cmake_install.cmake

**Comment by timohueser** [comment]
Hi Jonathan,

this is most likely caused by the CMake version not being recent enough. The [FAQ Section](https://github.com/JARVIS-MoCap/JARVIS-AcquisitionTool#faq) in the Readme has instructions on how to update to a recent version of CMake for Ubuntu 20.04 and 18.04. I'll add a disclaimer about this problem to the install instructions.

Thanks for reporting the issue and I hope this helps,
Timo
