### ISSUE TITLE
Trigger arduino not working

### ISSUE THREAD

**Issue by harshk95** [JARVIS-MoCap/JARVIS-AcquisitionTool#9]
Hi, 

I am trying to set up JARVIS! 
After following the current installation procedure including the installation of arduino firmare using PlatformIO, and wiring up the arduino upon start of the recording the arduino line6 does not emit any trigger pulses. I tried to upload myself on the arduino an old version of the trigger firmware and the recording starts but automatically stops after a very short time (around 1-2 minutes). 
I am using a Blackfly S camera and changed acquisition settings as mentioned in the instructions!

Thanks for your help and this very nice repo!

**Comment by JARVIS-MoCap** [comment]
Hi,

could you please try uploading the attached firmware the the Arduino and tell me if it still shuts down after a minute?

Best,
Timo

[Arduino_Trigger_Firmware.zip](https://github.com/JARVIS-MoCap/JARVIS-AcquisitionTool/files/9425690/Arduino_Trigger_Firmware.zip)

**Comment by harshk95** [comment]
Hi Timo,
Thanks a lot for the quick reply, it's up and running with this!

**Comment by timohueser** [comment]
That's great to hear! 
Sorry for the confusion, I was planning on transitioning the AcquisitionTool to the new PlatformIO based trigger firmware version but had to postpone it to iron out a few bugs. That's why you experienced those issues, I'll make sure to update the documentation accordingly soon.
